In [144]:
import pandas as pd

In [145]:
df = pd.read_csv('/content/WELFake_Dataset.csv.zip')

In [146]:
df

Unnamed: 0                                              title  \
0               0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...   
1               1                                                NaN   
2               2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
3               3  Bobby Jindal, raised Hindu, uses story of Chri...   
4               4  SATAN 2: Russia unvelis an image of its terrif...   
...           ...                                                ...   
72129       72129  Russians steal research on Trump in hack of U....   
72130       72130   WATCH: Giuliani Demands That Democrats Apolog...   
72131       72131  Migrants Refuse To Leave Train At Refugee Camp...   
72132       72132  Trump tussle gives unpopular Mexican leader mu...   
72133       72133  Goldman Sachs Endorses Hillary Clinton For Pre...   

                                                    text  label  
0      No comment is expected from Barack Obama Membe...      1  
1         Did they post their votes for Hillary already?      1  
2       Now, most of the demonstrators gathered last ...      1  
3      A dozen politically active pastors came here f...      0  
4      The RS-28 Sarmat missile, dubbed Satan 2, will...      1  
...                                                  ...    ...  
72129  WASHINGTON (Reuters) - Hackers believed to be ...      0  
72130  You know, because in fantasyland Republicans n...      1  
72131  Migrants Refuse To Leave Train At Refugee Camp...      0  
72132  MEXICO CITY (Reuters) - Donald Trump’s combati...      0  
72133  Goldman Sachs Endorses Hillary Clinton For Pre...      1  

[72134 rows x 4 columns]

In [147]:
df.shape

(72134, 4)

In [148]:
df.head()

Unnamed: 0                                              title  \
0           0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...   
1           1                                                NaN   
2           2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
3           3  Bobby Jindal, raised Hindu, uses story of Chri...   
4           4  SATAN 2: Russia unvelis an image of its terrif...   

                                                text  label  
0  No comment is expected from Barack Obama Membe...      1  
1     Did they post their votes for Hillary already?      1  
2   Now, most of the demonstrators gathered last ...      1  
3  A dozen politically active pastors came here f...      0  
4  The RS-28 Sarmat missile, dubbed Satan 2, will...      1

In [149]:
df.isnull().sum()

Unnamed: 0      0
title         558
text           39
label           0
dtype: int64

In [150]:
df=df.dropna()

In [151]:
df['id'] = df['Unnamed: 0']

/tmp/ipython-input-953776205.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['id'] = df['Unnamed: 0']


In [152]:
df

Unnamed: 0                                              title  \
0               0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...   
2               2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
3               3  Bobby Jindal, raised Hindu, uses story of Chri...   
4               4  SATAN 2: Russia unvelis an image of its terrif...   
5               5  About Time! Christian Group Sues Amazon and SP...   
...           ...                                                ...   
72129       72129  Russians steal research on Trump in hack of U....   
72130       72130   WATCH: Giuliani Demands That Democrats Apolog...   
72131       72131  Migrants Refuse To Leave Train At Refugee Camp...   
72132       72132  Trump tussle gives unpopular Mexican leader mu...   
72133       72133  Goldman Sachs Endorses Hillary Clinton For Pre...   

                                                    text  label     id  
0      No comment is expected from Barack Obama Membe...      1      0  
2       Now, most of the demonstrators gathered last ...      1      2  
3      A dozen politically active pastors came here f...      0      3  
4      The RS-28 Sarmat missile, dubbed Satan 2, will...      1      4  
5      All we can say on this one is it s about time ...      1      5  
...                                                  ...    ...    ...  
72129  WASHINGTON (Reuters) - Hackers believed to be ...      0  72129  
72130  You know, because in fantasyland Republicans n...      1  72130  
72131  Migrants Refuse To Leave Train At Refugee Camp...      0  72131  
72132  MEXICO CITY (Reuters) - Donald Trump’s combati...      0  72132  
72133  Goldman Sachs Endorses Hillary Clinton For Pre...      1  72133  

[71537 rows x 5 columns]

In [153]:
df = df.drop(['Unnamed: 0'], axis=1)


In [185]:
df['text'][72129]

'WASHINGTON (Reuters) - Hackers believed to be working for the Russian government broke into the Democratic National Committee’s computer network, spied on internal communications and accessed research on presumptive Republican presidential nominee Donald Trump, the committee and security experts said on Tuesday. Two separate groups entered the DNC’s system, and one read email and chat communications for nearly a year before being detected, according to the committee and CrowdStrike, the cyber firm that helped clean up the breach. Russian spies also targeted the networks of Trump and Democratic presidential candidate Hillary Clinton, as well as the computers of some Republican political action committees, the Washington Post quoted U.S. officials as saying, although details were not available. A Clinton campaign official said there was no evidence the campaign’s information systems had been hacked. A Russian government spokesman denied involvement in the breach. “I completely rule out 

In [154]:
df.head()

title  \
0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...   
2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
3  Bobby Jindal, raised Hindu, uses story of Chri...   
4  SATAN 2: Russia unvelis an image of its terrif...   
5  About Time! Christian Group Sues Amazon and SP...   

                                                text  label  id  
0  No comment is expected from Barack Obama Membe...      1   0  
2   Now, most of the demonstrators gathered last ...      1   2  
3  A dozen politically active pastors came here f...      0   3  
4  The RS-28 Sarmat missile, dubbed Satan 2, will...      1   4  
5  All we can say on this one is it s about time ...      1   5

In [155]:
X = df.drop('label',axis=1)
y = df['label']

In [156]:
X.shape

(71537, 3)

In [157]:
y.shape

(71537,)

In [158]:
import tensorflow as tf

In [159]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [160]:
### Vocabulary size
voc_size=5000

In [161]:
messages = X.copy()

In [162]:
messages = messages.reset_index()

In [163]:
messages

index                                              title  \
0          0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...   
1          2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
2          3  Bobby Jindal, raised Hindu, uses story of Chri...   
3          4  SATAN 2: Russia unvelis an image of its terrif...   
4          5  About Time! Christian Group Sues Amazon and SP...   
...      ...                                                ...   
71532  72129  Russians steal research on Trump in hack of U....   
71533  72130   WATCH: Giuliani Demands That Democrats Apolog...   
71534  72131  Migrants Refuse To Leave Train At Refugee Camp...   
71535  72132  Trump tussle gives unpopular Mexican leader mu...   
71536  72133  Goldman Sachs Endorses Hillary Clinton For Pre...   

                                                    text     id  
0      No comment is expected from Barack Obama Membe...      0  
1       Now, most of the demonstrators gathered last ...      2  
2      A dozen politically active pastors came here f...      3  
3      The RS-28 Sarmat missile, dubbed Satan 2, will...      4  
4      All we can say on this one is it s about time ...      5  
...                                                  ...    ...  
71532  WASHINGTON (Reuters) - Hackers believed to be ...  72129  
71533  You know, because in fantasyland Republicans n...  72130  
71534  Migrants Refuse To Leave Train At Refugee Camp...  72131  
71535  MEXICO CITY (Reuters) - Donald Trump’s combati...  72132  
71536  Goldman Sachs Endorses Hillary Clinton For Pre...  72133  

[71537 rows x 4 columns]

In [164]:
messages['title'][0]

'LAW ENFORCEMENT ON HIGH ALERT Following Threats Against Cops And Whites On 9-11By #BlackLivesMatter And #FYF911 Terrorists [VIDEO]'

In [165]:
import nltk
import re
from nltk.corpus import stopwords

In [166]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [167]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0,len(messages)):
  review = re.sub('[^a-zA-Z]',' ',messages['title'][i])
  review = review.lower()
  review = review.split()

  review  = [ps.stem(word)for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

In [168]:
corpus

['law enforc high alert follow threat cop white blacklivesmatt fyf terrorist video',
 'unbeliev obama attorney gener say charlott rioter peac protest home state north carolina video',
 'bobbi jindal rais hindu use stori christian convers woo evangel potenti bid',
 'satan russia unv imag terrifi new supernuk western world take notic',
 'time christian group sue amazon splc design hate group',
 'dr ben carson target ir never audit spoke nation prayer breakfast',
 'hous intel chair trump russia fake stori evid anyth video',
 'sport bar owner ban nfl game show true american sport like speak rural america video',
 'latest pipelin leak underscor danger dakota access pipelin',
 'gop senat smack punchabl alt right nazi internet',
 'may brexit offer would hurt cost eu citizen eu parliament',
 'schumer call trump appoint offici overse puerto rico relief',
 'watch hilari ad call question health age clinton crime famili boss',
 'chang expect espn polit agenda despit huge subscrib declin breitbart'

In [169]:
corpus[1]

'unbeliev obama attorney gener say charlott rioter peac protest home state north carolina video'

In [170]:
onehot_rep = [one_hot(words,voc_size)for words in corpus]
onehot_rep

[[4831, 305, 3303, 1751, 3331, 3851, 2087, 2613, 235, 3250, 366, 4540],
 [3285,
  4881,
  2864,
  2351,
  1915,
  2728,
  1546,
  275,
  427,
  4667,
  1016,
  802,
  2048,
  4540],
 [1113, 3561, 4864, 399, 2276, 3014, 1992, 2364, 2289, 1627, 4700, 3394],
 [636, 2105, 453, 3879, 1603, 4557, 2946, 1758, 4818, 3301, 1163],
 [2169, 1992, 4828, 2132, 3231, 334, 1733, 2469, 4828],
 [3830, 3417, 4272, 2362, 2539, 1928, 1812, 3142, 2661, 3880, 2202],
 [1423, 2628, 3459, 2547, 2105, 920, 3014, 4326, 2184, 4540],
 [4010,
  3612,
  209,
  4645,
  2107,
  1149,
  2086,
  307,
  440,
  4010,
  3265,
  4994,
  2096,
  4776,
  4540],
 [2046, 552, 4659, 2412, 1884, 1297, 1756, 552],
 [4822, 3589, 4064, 4426, 3797, 2508, 1995, 3537],
 [3274, 395, 3221, 343, 3963, 2747, 1530, 2129, 1530, 4715],
 [1919, 4361, 2547, 889, 3616, 3787, 3629, 2721, 1423],
 [507, 3810, 3691, 4361, 372, 2838, 1356, 2205, 4592, 4255, 3404],
 [3585, 1433, 3491, 899, 2088, 956, 3885, 2521, 2171, 4027],
 [3556, 2686, 1146, 1708, 3

In [171]:
onehot_rep[1]

[3285,
 4881,
 2864,
 2351,
 1915,
 2728,
 1546,
 275,
 427,
 4667,
 1016,
 802,
 2048,
 4540]

In [172]:
sent_length = 20
embedded_docs = pad_sequences(onehot_rep,padding='post',maxlen=sent_length)
print(embedded_docs)

[[4831  305 3303 ...    0    0    0]
 [3285 4881 2864 ...    0    0    0]
 [1113 3561 4864 ...    0    0    0]
 ...
 [ 714  813 3270 ...    0    0    0]
 [2547 2588 2337 ...    0    0    0]
 [3849 1859 1947 ...    0    0    0]]


In [173]:
embedded_docs[1]

array([3285, 4881, 2864, 2351, 1915, 2728, 1546,  275,  427, 4667, 1016,
        802, 2048, 4540,    0,    0,    0,    0,    0,    0], dtype=int32)

In [174]:
## Creating model
embedding_vector_features=40 ##features representation
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.build(input_shape=(None, sent_length))
model.summary()


Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)         │ (None, 20, 40)         │       200,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_8 (LSTM)                   │ (None, 100)            │        56,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 256,501 (1001.96 KB)

 Trainable params: 256,501 (1001.96 KB)

 Non-trainable params: 0 (0.00 B)

In [175]:
len(embedded_docs),y.shape

(71537, (71537,))

In [176]:
embedded_docs.shape,y.shape

((71537, 20), (71537,))

In [177]:
import numpy as np
X_final = np.array(embedded_docs)
y_final = np.array(y)

In [178]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_final,y_final,test_size=0.33,random_state=42)

In [179]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 29s 37ms/step - accuracy: 0.8030 - loss: 0.4038 - val_accuracy: 0.8910 - val_loss: 0.2573
Epoch 2/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 27s 36ms/step - accuracy: 0.9057 - loss: 0.2333 - val_accuracy: 0.8874 - val_loss: 0.2622
Epoch 3/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 27s 36ms/step - accuracy: 0.9206 - loss: 0.2026 - val_accuracy: 0.8932 - val_loss: 0.2645
Epoch 4/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 27s 36ms/step - accuracy: 0.9306 - loss: 0.1770 - val_accuracy: 0.8957 - val_loss: 0.2652
Epoch 5/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 41s 37ms/step - accuracy: 0.9395 - loss: 0.1543 - val_accuracy: 0.8951 - val_loss: 0.2674
Epoch 6/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 27s 36ms/step - accuracy: 0.9497 - loss: 0.1341 - val_accuracy: 0.8941 - val_loss: 0.2929
Epoch 7/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 27s 36ms/step - accuracy: 0.9545 - loss: 0.1167 - val_accuracy: 0.8943 - val_loss: 0.3157
Epoch 8/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 27s 36ms/step - accuracy: 0.9628 - loss: 0.0957 - 

In [180]:
y_pred = model.predict(X_test)
y_pred = np.where(y_pred>0.6,1,0)

738/738 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step


In [181]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy = accuracy_score(y_test,y_pred)
accuracy

0.8868603863097255

In [182]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.91      0.86      0.88     11693
           1       0.87      0.91      0.89     11915

    accuracy                           0.89     23608
   macro avg       0.89      0.89      0.89     23608
weighted avg       0.89      0.89      0.89     23608



Now that the model is trained, let's test it with some example text.